# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
#    parameter_name: value

services:
   admin.category:
      class: AppBundle\Admin\CategoryAdmin
      arguments: [~, AppBundle\Entity\Category, ~]
      tags:
          - { name: sonata.admin, manager_type: orm, label: Category }
      public: true

   admin.blog_post:
      class: AppBundle\Admin\BlogPostsAdmin
      arguments: [~, AppBundle\Entity\BlogPost, ~]
      tags:
          - { name: sonata.admin, manager_type: orm, label: Blog posts }
      public: true
